// Unified course data to be used across the site
export const courses = [
  {
    id: "blockchain-basics",
    title: "Blockchain Basics",
    description: "Learn the fundamentals of blockchain technology and how it works",
    image: "/images/courses/blockchain-basics.png",
    category: "blockchain",
    level: "Beginner",
    duration: "4 weeks",
    xp: 3000,
    tokens: 300,
    icon: "blocks",
  },
  {
    id: "web-design-web3",
    title: "Web Design for Web3 Apps",
    description: "Master the art of designing user interfaces for decentralized applications",
    image: "/images/courses/web-design-web3.png",
    category: "design",
    level: "Intermediate",
    duration: "6 weeks",
    xp: 4500,
    tokens: 450,
    icon: "design",
  },
  {
    id: "solana-development",
    title: "Solana Development",
    description: "Build high-performance applications on the Solana blockchain",
    image: "/images/courses/solana-development.png",
    category: "development",
    level: "Advanced",
    duration: "8 weeks",
    xp: 6000,
    tokens: 600,
    icon: "code",
  },
  {
    id: "ethereum-blockchain",
    title: "Ethereum Blockchain",
    description: "Dive deep into Ethereum's architecture, smart contracts, and ecosystem",
    image: "/images/courses/ethereum-blockchain.png",
    category: "blockchain",
    level: "Intermediate",
    duration: "7 weeks",
    xp: 5000,
    tokens: 500,
    icon: "ethereum",
  },
  {
    id: "smart-contract-security",
    title: "Smart Contract Security",
    description: "Learn to identify vulnerabilities and secure your smart contracts",
    image: "/images/courses/smart-contract-security.png",
    category: "security",
    level: "Advanced",
    duration: "5 weeks",
    xp: 5500,
    tokens: 550,
    icon: "shield",
  },
  {
    id: "create-memecoin",
    title: "Create Your Own Memecoin",
    description: "Step-by-step guide to creating, launching, and marketing a memecoin",
    image: "/images/courses/create-memecoin.png",
    category: "crypto",
    level: "Intermediate",
    duration: "3 weeks",
    xp: 3500,
    tokens: 350,
    icon: "coin",
  },
  {
    id: "full-stack-web3",
    title: "Full-Stack Web3 Development",
    description: "Learn to build decentralized applications from scratch",
    image: "/images/courses/full-stack-web3.png",
    category: "development",
    level: "Intermediate",
    duration: "8 weeks",
    xp: 5000,
    tokens: 500,
    icon: "code",
  },
  {
    id: "react-for-web3",
    title: "React for Web3",
    description: "Build modern UIs for blockchain applications",
    image: "/images/courses/react-for-web3.png",
    category: "development",
    level: "Beginner",
    duration: "4 weeks",
    xp: 3000,
    tokens: 300,
    icon: "code",
  },
  {
    id: "defi-masterclass",
    title: "DeFi Masterclass",
    description: "Explore decentralized finance protocols and applications",
    image: "/images/courses/defi-masterclass.png",
    category: "blockchain",
    level: "Intermediate",
    duration: "5 weeks",
    xp: 4000,
    tokens: 400,
    icon: "ethereum",
  },
]

// For the homepage featured courses
export const featuredCourses = {
  tech: [
    courses.find((course) => course.id === "full-stack-web3"),
    courses.find((course) => course.id === "smart-contract-security"),
    courses.find((course) => course.id === "react-for-web3"),
  ].filter(Boolean),
  blockchain: [
    courses.find((course) => course.id === "blockchain-basics"),
    courses.find((course) => course.id === "defi-masterclass"),
    courses.find((course) => course.id === "create-memecoin"),
  ].filter(Boolean),
}
